config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  # Defines the about path route ("/about")
  get "/about", to: "pages#about"

  # Defines the articles path route ("/articles")
  resources :articles # , only: [:show, :index, :create, :new, :edit, :update, :destroy] => Restful Routes => https://guides.rubyonrails.org/routing.html#crud-verbs-and-actions

  # Defines the signup path route ("/signup")
  get "/signup", to: "users#new"

  #Defines the login path route ("/login")
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  #Defines the logout path route ("/logout")
  delete "/logout", to: "sessions#destroy"

  # Defines the users path route ("/users")
  resources :users, except: [:new] # => Restful Routes

  # Categories routes
  resources :categories, except: [:destroy] # => except: [:destroy] => because we don't want to allow users to delete categories from the front end

  # 404 page
  get "*path", to: "pages#not_found", constraints: lambda { |req| req.path.exclude? "rails/active_storage" }
end


# except and only are options that can be passed to the resources method to specify which routes to generate
# except: [:new] will generate all routes except the new route
# only: [:new] will generate only the new route

# The routes generated by the resources method are as follows:
# GET /users => users#index
# GET /users/new => users#new
# POST /users => users#create
# GET /users/:id => users#show
# GET /users/:id/edit => users#edit
# PATCH /users/:id => users#update
# PUT /users/:id => users#update
# DELETE /users/:id => users#destroy

# constraints: lambda { |req| req.path.exclude? "rails/active_storage" } is used to exclude the routes generated by the resources method for Active Storage 
# lambda { |req| req.path.exclude? "rails/active_storage" } is a lambda function that takes in a request object and returns true if the path does not include "rails/active_storage" and false otherwise
# req.path is the path of the request object
# req.path.exclude? "rails/active_storage" returns true if the path of the request object does not include "rails/active_storage" and false otherwise

app/models/article.rb
class Article < ApplicationRecord
    # Validations
    validates :title, presence: true, length: { minimum: 5, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 500 }

    # Associations
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :get_article_by_id, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    def show
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 6)
    end

    def new 
        @article = Article.new
    end

    def create
        #debugger
        #params.require(:article) is a hash that looks like this:
        # {
        #     "title" => "My Article",
        #     "description" => "My article description",
        #     "author" => "My article author"
        # }

        # params.require(:article).permit(:title, :description) is a hash that looks like this:
        # {
        #     "title" => "My Article",
        #     "description" => "My article description"
        # }

        @article = Article.new(article_params)
        @article.user = current_user
        result = @article.save
        if result
            #flash is a hash that looks like this and is used to display messages to the user this message is shown in app/views/layouts/application.html.erb
            # {
            #     "notice" => "Article was created successfully."
            # }

            flash[:notice] = "Article was created successfully."
            redirect_to @article
            # format.json { render json: @article, status: :created, location: @article }
        else
            return render(:new, status: :unprocessable_entity, locals: { article: @article }) unless result
        end
    end

    def edit
    end

    def update

        result = @article.update(article_params)
        if result
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
        else
            return render(:edit, status: :unprocessable_entity, locals: { article: @article }) unless result
            # Here we are rendering the edit.html.erb view file and passing in the article object as a local variable
            # Here Status: :unprocessable_entity is the HTTP status code for an unprocessable entity (422)
            # https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
        end
    end
    
    def destroy
        @article.destroy
        flash[:notice] = "Article was deleted successfully."
        redirect_to articles_path
    end

    private

        def get_article_by_id
            result = Article.exists?(params[:id])
            if result
                @article = Article.find(params[:id])
            else
                flash[:alert] = "Article with id #{params[:id]} does not exist."
                redirect_to articles_path
            end
        end

        def article_params
            params.require(:article).permit(:title, :description, category_ids: [])
        end

        def require_same_user
            if current_user != @article.user && current_user.usertype != "admin"
                flash[:alert] = "You can only edit or delete your own article."
                redirect_to @article
            end
        end
end

app/views/articles/_article.html.erb
<% if obj.empty? %>
  <p
  class="text-center d-flex flex-column align-items-center justify-content-center"
  >
    <%= image_tag "no_articles_found.svg", alt: "No articles found", width: "50%", height: "80%" %>
    <span class="text-center mt-3"
    style="font-size: 1.5rem; font-weight: 600;"
    >No articles found!</span>
  <% end %>
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-3">
    <% obj.each do |article| %>
      <div class="col" style="height: 210px !important">
        <div class="card shadow h-100">
          <div class="card-body">
            <%# Categories Badge %>
            <div class="d-flex flex-wrap gap-2 mb-2">
              <%= render article.categories %>
            </div>
            <h5 class="card-title"><%= article.title %></h5>
            <p class="card-text"><% if article.description.length > 40 %></p>
              <p class="card-text"><%= article.description.slice(0, 40) %>...</p>
            <% else %>
              <p class="card-text"><%= article.description %></p>
            <% end %>
            <p class="card-text"><%= article.user.username if article.user %></p>
            <div class="btn-container d-flex gap-2">
              <%= link_to 'Go to Article', article_path(article), class: "btn btn-outline-primary" %>
              <% if logged_in? && (current_user == article.user || current_user.usertype == "admin") %>
                <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-success" %>
                <%= button_to 'Delete', article_path(article), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/articles/_errors.html.erb
<%# flash messages %>
<% if @article.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible fade show" role="alert">
        <h2 class="alert-heading">
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
        </h2>
        <ul class="mb-0">
            <% @article.errors.full_messages.each do |msg| %>
                <li class="mb-0">
                <%= msg %>
                </li>
            <% end %>
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%= render "shared/errors", data: @article %>
<%= form_with(model: @article, local: true, class: "form") do |form| %>
  <div class="form-label">
    <%= form.label :title, "Title", class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-label">
    <%= form.label :description, "Description", class: "form-label" %>
    <%= form.text_area :description, class: "form-control", rows: 10, cols: 10%>
  </div>

  <%# User can select multiple categoriesin bubble fo %>
  <div class="form-label">
    <%= form.label :category_ids, "Categories", class: "form-label" %> (To select multiple categories, hold down the Ctrl (windows) / Command (Mac) button while clicking on the categories)
    <%= form.collection_select :category_ids, Category.all, :id, :name, {prompt: "You can select multiple categories"}, {multiple: true, size:8, class: "form-control custom-select rounded"} %>
  </div>
  
  <div class="form-label">
    <%= form.submit "Submit", class: "btn btn-outline-primary",
         style: "width: 10%; margin-top: 20px;"
        %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render "form" %>

<div class="mt-4">
<%= link_to 'Back to all Articles', articles_path, class: "btn btn-primary" %>
</div>

app/views/articles/index.html.erb
<h1>All Articles</h1>
<%= render "article", obj:@articles %>
<div class="flickr_pagination mt-4">
  <%= will_paginate @articles, :container => false %>
</div>
<div class="mt-4">
  <%= link_to 'Create a new Article', (logged_in? ? new_article_path : login_path), class: "btn btn-primary" %>
</div>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render "form" %>

<div class="mt-4">
<%= link_to 'Back to all Articles', articles_path, class: "btn btn-primary" %>
</div>

app/views/articles/show.html.erb
<h1>Article's Details</h1>

<div class="card shadow">
  <div class="card-body">
    <%# Categories Badge %>
    <div class="d-flex flex-wrap gap-2 mb-2">
    <%= render @article.categories %>
    </div>
    <h5 class="card-title"><%= @article.title %></h5>
    <p class="card-text"><%= @article.description %></p>
    <p class="card-text"><%= @article.user.username %></p>
    <div class="btn-container d-flex gap-2">
    <% if logged_in? && (current_user == @article.user || current_user.usertype == "admin") %>
    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-success" %>
    <%= button_to 'Delete', article_path(@article), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
    <% end %>
  </div></div>
</div>

<div class="mt-4">
<%= link_to 'Back to all Articles', articles_path, class: "btn btn-primary" %>
</div>