config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  # Defines the about path route ("/about")
  get "/about", to: "pages#about"

  # Defines the articles path route ("/articles")
  resources :articles # , only: [:show, :index, :create, :new, :edit, :update, :destroy] => Restful Routes => https://guides.rubyonrails.org/routing.html#crud-verbs-and-actions

  # Defines the signup path route ("/signup")
  get "/signup", to: "users#new"

  #Defines the login path route ("/login")
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  #Defines the logout path route ("/logout")
  delete "/logout", to: "sessions#destroy"

  # Defines the users path route ("/users")
  resources :users, except: [:new] # => Restful Routes

  # Categories routes
  resources :categories, except: [:destroy] # => except: [:destroy] => because we don't want to allow users to delete categories from the front end

  # 404 page
  get "*path", to: "pages#not_found", constraints: lambda { |req| req.path.exclude? "rails/active_storage" }
end


# except and only are options that can be passed to the resources method to specify which routes to generate
# except: [:new] will generate all routes except the new route
# only: [:new] will generate only the new route

# The routes generated by the resources method are as follows:
# GET /users => users#index
# GET /users/new => users#new
# POST /users => users#create
# GET /users/:id => users#show
# GET /users/:id/edit => users#edit
# PATCH /users/:id => users#update
# PUT /users/:id => users#update
# DELETE /users/:id => users#destroy

# constraints: lambda { |req| req.path.exclude? "rails/active_storage" } is used to exclude the routes generated by the resources method for Active Storage 
# lambda { |req| req.path.exclude? "rails/active_storage" } is a lambda function that takes in a request object and returns true if the path does not include "rails/active_storage" and false otherwise
# req.path is the path of the request object
# req.path.exclude? "rails/active_storage" returns true if the path of the request object does not include "rails/active_storage" and false otherwise

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase } #before saving to db, convert email to lowercase

    #Validations
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i #regex for email validation
    validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }

    # Associations
    has_many :articles, dependent: :destroy #if user is deleted, all articles associated with user are deleted

    # Password encryption
    has_secure_password #adds password_digest column to db and allows us to save a securely hashed password_digest attribute to the database
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :get_user_by_id, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index, :new, :create]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @users = User.paginate(page: params[:page], per_page: 6)
    end

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        result = @user.save
        if result
            flash[:notice] = "Welcome to the Alpha Blog, #{user_params[:username]}!, you have successfully signed up."
            session[:user_id] = @user.id
            redirect_to @user
            # debugger
        else
            return render(:new, status: :unprocessable_entity, locals: { user: @user }) unless result
        end
    end

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 6)
    end

    def edit
    end

    def update
        result = @user.update(user_params)
        if result
            flash[:notice] = "Hi, #{user_params[:username]}!, you have successfully updated your account."
            redirect_to @user
        else
            return render(:edit, status: :unprocessable_entity, locals: { user: @user }) unless result
        end
    end

    def destroy
        @user.destroy
        if current_user.usertype == "admin"
            flash[:notice] = "The user and all associated articles have been deleted."
            redirect_to users_path
        else
            session[:user_id] = nil
            flash[:notice] = "Your account and all associated articles have been deleted."
            redirect_to root_path
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def get_user_by_id
        result = User.find_by_id(params[:id])
        if result
            @user = result
        else
            flash[:alert] = "User with id #{params[:id]} does not exist."
            redirect_to users_path
        end
    end

    def require_same_user
        if current_user != @user && current_user.usertype != "admin"
            flash[:alert] = "You can only edit or delete your own account."
            redirect_to @user
        end
    end

end

# return render(:edit, status: :unprocessable_entity, locals: { user: @user }) unless result
# Here we are rendering the edit.html.erb view file and passing in the user object as a local variable for the edit view file to use
# The status: :unprocessable_entity is the HTTP status code that will be returned to the browser
# The status: :unprocessable_entity is the HTTP status code for an unprocessable entity (422)
# An unprocessable entity is an entity that cannot be processed by the server because it is not in the correct format

app/views/users/_form.html.erb
<%= render "shared/errors", data: @user %>

<%= form_with(model:@user, local: true, class: "my-form") do |form| %>

  <div class="email-input">
    <span class="material-icons-round icon-size"> person_outline </span>
    <span id="seperator"></span>
    <div class="input-container">
      <p><%= form.label :username, class: "sub-title" %></p>
      <%= form.text_field :username, class: "username" %>
    </div>
  </div>
  <div class="email-input">
    <span class="material-icons-round icon-size"> mail_outline </span>
    <span id="seperator"></span>
    <div class="input-container">
      <p><%= form.label :email, class: "sub-title" %></p>
      <%= form.email_field :email, class: "email" %>
    </div>
  </div>
  <div class="email-input">
    <span class="material-icons-round icon-size"> password </span>
    <span id="seperator"></span>
    <div class="input-container">
      <p><%= form.label :password, class: "sub-title" %></p>
      <%= form.password_field :password, class: "password" %>
    </div>
  </div>
  <%= form.submit "Continue", id: "submit" %>
<% end %>

app/views/users/edit.html.erb
<section class="form-parent-container">
  <article class="form-container">
    <div class="intro">
      <h1>Edit your profile information</h1>
    </div>
    <%= render "form"%>
  </article>
</section>

app/views/users/index.html.erb
<h1>Alpha Bloggers</h1>

<% if @users.empty? %>
  <p
  class="text-center"
  >There are no users yet. <%= link_to 'Create one!', new_user_path %></p>
<% end %>

<div class="row">
  <% @users.each do |user| %>
    <div class="col-lg-4">
      <div class="card mb-4">
        <div class="card-body text-center">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
              class="rounded-circle img-fluid" style="width: 150px; border: 5px solid whitesmoke;">
          <h5 class="my-3"><%= user.username %><% if current_user.usertype == "admin" %> (<%= user.usertype.capitalize %>)<% end %><p class="text-muted mb-1">(<%= pluralize(user.articles.count, "article") %>)</p></h5>
          <p class="text-muted mb-1">Full Stack Developer</p>
          <p class="text-muted mb-4"><%= user.email %></p>
          <div class="d-flex justify-content-center mb-2">
            <%= link_to 'View Profile', user_path(user), class: "btn btn-outline-success ms-1" %>
            <% if logged_in? %>
            <% if current_user == user  %>
            <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-outline-primary ms-1" %>
            <% end %>
            <% if current_user.usertype == "admin" %>
            <%= button_to "Delete Account", user_path(user), method: :delete, data: { turbo_confirm: "Are you sure you want to delete your account?" }, class: "btn btn-outline-danger ms-1" %>
            <%end%>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mt-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<%# Sign Up Form %>
    <section class="form-parent-container">
      <article class="form-container">
        <div class="intro">
            <h1>Sign Up</h1>
            <p>Already have an account? <a href="/login">Log In</a></p>
        </div>

        <%= render "form"%>
      </article>
    </section>

app/views/users/show.html.erb
<%# <h1>User Profile</h1> %>
<div class="row">
  <div class="col-lg-12">
    <div class="card mb-4">
      <div class="card-image">
        <img src="https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/media/banner.ef572d78f29b0fee0a09.png" class="img-fluid rounded-3 position-absolute z-0
        " alt="user profile"
        style="top: 25%; left: 50%; transform: translate(-50%, -50%);
        height: 170px; object-fit: cover; width: 98%;
        "
        >
      </div>
      <div class="card-body text-center position-relative z-2">
        <%# Delete Account %>
        <% if logged_in? && (current_user == @user || current_user.usertype == "admin") %>
          <div class="row" style="position: absolute; top: 20px; right: 20px; cursor: pointer;">
            <div class="col-lg-12 text-center">
              <%= button_to "Delete Account", user_path(@user), method: :delete, data: { turbo_confirm: "Are you sure you want to delete your account?" }, class: "btn btn-danger" %>
            </div>
          </div>
        <% end %>
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
              class="rounded-circle img-fluid" style="width: 200px; height: 200px; object-fit: cover; border: 5px solid white;">
        <h5 class="my-3"><%= @user.username %><%= "(Admin)" if @user.usertype == "admin" %></h5>
        <p class="text-muted mb-1">Full Stack Developer</p>
        <p class="text-muted mb-4"><%= @user.email %></p>
        <div class="d-flex justify-content-center mb-2">
          <% if logged_in? && current_user == @user %>
            <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-outline-primary ms-1" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%# Show all user article %>
  <% if logged_in? && (current_user == @user || current_user.usertype == "admin") && @user.articles.empty? %>
    <div class="col-lg-12 text-center">
      <h3>Oopss! You have not created any article yet.</h3>
      <%= link_to "Create one now!", new_article_path, class: "btn btn-primary" %>
    </div>
  <% elsif @user.articles.empty? %>
    <%= render "shared/articles_not_found" %>
  <%else%>
    <h3 class="text-center mb-4">Articles</h3>
    <%= render "articles/article", obj: @user.articles %>
  <% end %>
</div>
<div class="flickr_pagination mt-4">
  <%= will_paginate @articles, :container => false %>
</div>