config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  # Defines the about path route ("/about")
  get "/about", to: "pages#about"

  # Defines the articles path route ("/articles")
  resources :articles # , only: [:show, :index, :create, :new, :edit, :update, :destroy] => Restful Routes => https://guides.rubyonrails.org/routing.html#crud-verbs-and-actions

  # Defines the signup path route ("/signup")
  get "/signup", to: "users#new"

  #Defines the login path route ("/login")
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  #Defines the logout path route ("/logout")
  delete "/logout", to: "sessions#destroy"

  # Defines the users path route ("/users")
  resources :users, except: [:new] # => Restful Routes

  # Categories routes
  resources :categories, except: [:destroy] # => except: [:destroy] => because we don't want to allow users to delete categories from the front end

  # 404 page
  get "*path", to: "pages#not_found", constraints: lambda { |req| req.path.exclude? "rails/active_storage" }
end


# except and only are options that can be passed to the resources method to specify which routes to generate
# except: [:new] will generate all routes except the new route
# only: [:new] will generate only the new route

# The routes generated by the resources method are as follows:
# GET /users => users#index
# GET /users/new => users#new
# POST /users => users#create
# GET /users/:id => users#show
# GET /users/:id/edit => users#edit
# PATCH /users/:id => users#update
# PUT /users/:id => users#update
# DELETE /users/:id => users#destroy

# constraints: lambda { |req| req.path.exclude? "rails/active_storage" } is used to exclude the routes generated by the resources method for Active Storage 
# lambda { |req| req.path.exclude? "rails/active_storage" } is a lambda function that takes in a request object and returns true if the path does not include "rails/active_storage" and false otherwise
# req.path is the path of the request object
# req.path.exclude? "rails/active_storage" returns true if the path of the request object does not include "rails/active_storage" and false otherwise

app/models/category.rb
class Category < ApplicationRecord
    # validations
    validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }

    # associations
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update]
    before_action :require_user, except: [:index, :show]
    before_action :require_admin, except: [:index, :show]

    def index
        @categories = Category.paginate(page: params[:page], per_page: 6)
    end

    def new
        @category = Category.new
    end
    
    def create
        # create a new category with the name from the form
        # if the category is saved, redirect to the category show page
        # if the category is not saved, render the new category form again

        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "The category has been created."
            redirect_to @category
        else
            return render(:new, status: :unprocessable_entity, locals: { category: @category })
        end
    end

    def show
        @categories = Category.paginate(page: params[:page], per_page: 6)
    end

    def edit
    end

    def update
        if @category.update(category_params)
            flash[:notice] = "The category has been updated."
            redirect_to @category
        else
            return render(:edit, status: :unprocessable_entity, locals: { category: @category })
        end
    end

    private
    def category_params
        params.require(:category).permit(:name)
    end

    def set_category
        @category = Category.find(params[:id])
    end

    def require_admin
        if !logged_in? || (logged_in? && !(current_user.usertype == "admin"))
            flash[:alert] = "Only admins can perform that action."
            redirect_to categories_path
        end
    end

end

app/views/categories/_category.html.erb
 <%# Categories Badge %>
<%= link_to category.name, category_path(category), class: "badge bg-primary text-white text-decoration-none" %>

app/views/categories/_form.html.erb
<%= render "shared/errors", data: @category %>
<%= form_with(model:@category, remote: true, class: "my-form") do |form| %>
  <div class="email-input">
    <span class="material-icons-round icon-size"> category </span>
    <span id="seperator"></span>
    <div class="input-container">
      <p><%= form.label :name, "Category Name", class: "sub-title" %></p>
      <%= form.text_field :name, class: "name" %>
    </div>
  </div>
  <%= form.submit "Continue", id: "submit" %>
<% end %>

app/views/categories/edit.html.erb
<section class="form-parent-container">
  <article class="form-container">
    <div class="intro">
      <h1>Edit Category</h1>
      <p class="sub-title">Edit a category to organize your posts</p>
    </div>
    <%= render "form"%>
  </article>
</section>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% if @categories.empty? %>
  <p
  class="text-center"
  >There are no categories yet. <%= link_to 'Create one!', new_category_path %></p>
<% end %>

<div class="row">
  <% @categories.each do |category| %>
    <div class="col-lg-4">
      <div class="card mb-4">
        <div class="card-body text-center">
          <h5 class="my-3"><%= link_to category.name, category_path(category) %></h5>
            <p class="text-muted"><%= pluralize(category.articles.count, "article") %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mt-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<%# Sign Up Form %>
<section class="form-parent-container">
  <article class="form-container">
    <div class="intro">
        <h1 class="title">Create a Category</h1>
        <p class="sub-title">Create a category to organize your posts</p>
    </div>
    <%= render "form"%>
  </article>
</section>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %> <span style="font-size: 25px;"> (<%= link_to "Edit", edit_category_path(@category)%>)</span></h1>

  <%# Show all user article %>
  <% if logged_in? && (current_user == @user || current_user.usertype == "admin") && @category.articles.empty? %>
    <div class="col-lg-12 text-center">
      <h3>Oopss! You have not created any article yet.</h3>
      <%= link_to "Create one now!", new_article_path, class: "btn btn-primary" %>
    </div>
  <% elsif @category.articles.empty? %>
    <%= render "shared/articles_not_found" %>
  <%else%>
    <h3 class="text-center mb-4">Articles</h3>
    <%= render "articles/article", obj: @category.articles %>
  <% end %>
</div>
<div class="flickr_pagination mt-4">
  <%= will_paginate @articles, :container => false %>
</div>