config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  # Defines the about path route ("/about")
  get "/about", to: "pages#about"

  # Defines the articles path route ("/articles")
  resources :articles # , only: [:show, :index, :create, :new, :edit, :update, :destroy] => Restful Routes => https://guides.rubyonrails.org/routing.html#crud-verbs-and-actions

  # Defines the signup path route ("/signup")
  get "/signup", to: "users#new"

  #Defines the login path route ("/login")
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  #Defines the logout path route ("/logout")
  delete "/logout", to: "sessions#destroy"

  # Defines the users path route ("/users")
  resources :users, except: [:new] # => Restful Routes

  # Categories routes
  resources :categories, except: [:destroy] # => except: [:destroy] => because we don't want to allow users to delete categories from the front end

  # 404 page
  get "*path", to: "pages#not_found", constraints: lambda { |req| req.path.exclude? "rails/active_storage" }
end


# except and only are options that can be passed to the resources method to specify which routes to generate
# except: [:new] will generate all routes except the new route
# only: [:new] will generate only the new route

# The routes generated by the resources method are as follows:
# GET /users => users#index
# GET /users/new => users#new
# POST /users => users#create
# GET /users/:id => users#show
# GET /users/:id/edit => users#edit
# PATCH /users/:id => users#update
# PUT /users/:id => users#update
# DELETE /users/:id => users#destroy

# constraints: lambda { |req| req.path.exclude? "rails/active_storage" } is used to exclude the routes generated by the resources method for Active Storage 
# lambda { |req| req.path.exclude? "rails/active_storage" } is a lambda function that takes in a request object and returns true if the path does not include "rails/active_storage" and false otherwise
# req.path is the path of the request object
# req.path.exclude? "rails/active_storage" returns true if the path of the request object does not include "rails/active_storage" and false otherwise

app/views/layouts/_footer.html.erb
<footer class="flex-shrink-0 py-3 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; 2023</small> Developed by <%= link_to "Harsh Kumar", "https://w3villa-harsh-kumar.github.io/My-Portfolio/", target:
        "_blank", rel: "noopener noreferrer", class: "text-white" %>
    </div>
</footer> 

app/views/layouts/_messages.html.erb
<%# Flash Message %>
<% flash.each do |name, msg|
%>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light border-bottom">
  <div class="container-fluid">
    <%= link_to "Alpha Blog", root_path, class: "navbar-brand text-primary fw-bold" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%# 
        current_page?(route) => true if the current page is the route otherwise false
         %>
          <% if current_page?(root_path) %>
            <%= link_to 'Home', root_path, class: "nav-link active" %>
          <% else %>
            <%= link_to 'Home', root_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if current_page?(about_path) %>
            <%= link_to 'About', about_path, class: "nav-link active" %>
          <% else %>
            <%= link_to 'About', about_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if current_page?(articles_path) %>
            <%= link_to 'All Articles', articles_path, class: "nav-link active" %>
          <% else %>
            <%= link_to 'All Articles', articles_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if logged_in? %>
            <% if current_user.usertype == "admin" %>

                <div class="d-flex">
                <% if current_page?(categories_path) %>
                <%= link_to 'All Categories', categories_path, class: "nav-link active" %>
                <% else %>
                <%= link_to 'All Categories', categories_path, class: "nav-link" %>
                <% end %>

                <% if current_page?(new_category_path) %>
                <%= link_to 'New Category', new_category_path, class: "nav-link active" %>
                <% else %>
                <%= link_to 'New Category', new_category_path, class: "nav-link" %>
                <% end %>
                
                <% if current_page?(users_path) %>
                    <%= link_to 'Bloggers', users_path, class: "nav-link active" %>
                  <% else %>
                    <%= link_to 'Bloggers', users_path, class: "nav-link" %>
                  <% end %>
                </div>
            <% end %>

            <% if current_user.usertype != "admin" %>
                <div class="d-flex">
                <% if current_page?(categories_path) %>
                <%= link_to 'All Categories', categories_path, class: "nav-link active" %>
                <% else %>
                <%= link_to 'All Categories', categories_path, class: "nav-link" %>
                <%end%>

                <% if current_page?(users_path) %>
                    <%= link_to 'Bloggers', users_path, class: "nav-link active" %>
                  <% else %>
                    <%= link_to 'Bloggers', users_path, class: "nav-link" %>
                  <% end %>
                </div>
            <%end%>
          <% end %>
        </li>
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">Search</button>
      </form> %>
      <div class="links-container d-flex justify-content-center align-items-center gap-2">
        <% if logged_in? %>
          <%= link_to (((current_user.username + " (Admin)") if current_user.usertype == "admin") || current_user.username + " (Blogger)"), current_user, class: "text-primary ms-1" %>
          <%= button_to "Log out", logout_path, method: :delete, class: "btn btn-outline-primary ms-1" %>
        <% else %>
          <%= link_to "Sign up", signup_path, class: "btn btn-outline-primary ms-1" %>
          <%= link_to "Log in", login_path, class: "btn btn-outline-primary ms-1" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link
      href="https://fonts.googleapis.com/css2?family=Material+Icons+Round"
      rel="stylesheet"
    />
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navbar" %>
    <%= render "layouts/messages" %>
    <div id="page-content">
    <div class="container my-5">
    <%= yield %>
    </div>
    </div>
    <%= render "layouts/footer" %>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </body>
</html>